#!/usr/bin/env python
import sys
import os

fn_include = sys.argv[1]
fn_header = fn_include.lower() + ".hpp"
fn_code = fn_include.lower() + ".cpp"

path_include = os.path.join("src", fn_include)
path_header = os.path.join("src", fn_header)
path_code = os.path.join("src", fn_code)
with open(path_include, "w") as fp:
    fp.write("#include \"{}\"".format(fn_header))
with open(path_header, "w") as fp:
    fp.write("#ifndef {0}_HPP\n#define {0}_HPP\n\n\n\n#endif".format(
        fn_include.upper()))
with open(path_code, "w") as fp:
    fp.write("#include \"{}\"\n".format(fn_header))
